---
- hosts: all
  become: true
  tasks:

  - name: Устанавливаем epel-репозиторий
    yum:
      name: epel-release
      state: present
    tags:
      - epel-package
      - packages

  - name: install packages
    yum:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - bind
      - bind-utils
      - mc
      - nano
      - openvpn
      - iperf3
      - sshpass
      - easy-rsa

  - name: Создаем конфигурацию OVPN
    template:
      src: server.conf
      dest: /etc/openvpn/server.conf


